### ISSUE TITLE
The model predicts the relationship of all entities as "N", that is, no relationship.

### ISSUE THREAD

**Issue by yuanxiaosc** [bekou/multihead_joint_entity_relation_extraction#11]
Because the data labeling strategy according to the multi-head selection model, most of the relationship labels are "N", which leads to the model biasing the prediction of "N". How to solve such a problem?

**Comment by bekou** [comment]
Well this is not an issue in any of our examined datasets. We have examined four datasets in our work. I guess you use your own dataset. You can try to weight the examples to solve your imbalanced problem. Another solution might be to remove the N label completely from the model (i.e., you have to change the model for that). Basically, you get probabilities for each of the labels and when for every of the examined labels, you get a threshold below 0.5, you can infer that there is no relation. This is just an idea and I am not sure whether it will work in practice.

**Comment by mangonihao** [comment]
uaho1
