### ISSUE TITLE
About ADE data set

### ISSUE THREAD

**Issue by nlp-wh** [bekou/multihead_joint_entity_relation_extraction#13]
Hello, I am a bioinformatics student. 

Can I request a dataset of ADE adapted to the input format? Or can I request the open source code that processes these original dataset?

I guarantee that the above data or code is for the laboratory only and does not involve any commercial activities.

Best Regards,

**Comment by bekou** [comment]
Could you please send me a mail for that? I am not sure if I can distribute it from my github codebase.

**Comment by nlp-wh** [comment]
Ok, I have sent a mail to the email address provided in your paper, please check

**Comment by kamalkraj** [comment]
@bekou 
Could you please share the ADE data or script to convert ADE data to format that supported by your code .

**Comment by bekou** [comment]
@kamalkraj Could you please send me a mail for that?

**Comment by kamalkraj** [comment]
@bekou 
I mailed to email address given in your paper

**Comment by ChloeJKim** [comment]
I also emailed to the address in your paper
