### ISSUE TITLE
Saving and Restoring the model

### ISSUE THREAD

**Issue by EvilPort2** [bekou/multihead_joint_entity_relation_extraction#3]
Hello. I am newbie to tensorflow. How do I save the model so that I can use it later? I tried tf.train.Saver() within the session but it says ValueError: No variables to save

**Comment by bekou** [comment]
Hi Eviport2, this is a TensorFlow related issue. You can take a look [here](https://www.tensorflow.org/guide/saved_model) for more info.

**Comment by zwd13122889** [comment]
> Hello. I am newbie to tensorflow. How do I save the model so that I can use it later? I tried tf.train.Saver() within the session but it says ValueError: No variables to save

Can you save the model? I want to know how to save.thx.
