### ISSUE TITLE
[error when trying to change batchsize]

### ISSUE THREAD

**Issue by dirtdust** [bekou/multihead_joint_entity_relation_extraction#4]
First of all, thank you very much for such a great work. 
Hmm, I am trying to run your code, but I found that the batchsize in "build_data.py" is "1",  I tried to set it to "20", then I got an error which said "ValueError: setting an array element with a sequence."
Can you help me with that?

**Comment by bekou** [comment]
@dirtdust The parameters that are allowed to be modified for the model are specified in the configuration files (see for [CoNLL04](https://github.com/bekou/multihead_joint_entity_relation_extraction/tree/master/configs/CoNLL04)). Currently, the code supports only batch sizes equal to 1.

**Comment by dirtdust** [comment]
> @dirtdust The parameters that are allowed to be modified for the model are specified in the configuration files (see for [CoNLL04](https://github.com/bekou/multihead_joint_entity_relation_extraction/tree/master/configs/CoNLL04)). Currently, the code supports only batch sizes equal to 1.

@bekou thanks for replying. I see, but if we can only set batch size to "1", how can we optimize the loss , I am  confused here.

**Comment by bekou** [comment]
@dirtdust basically I don't see any problem for computing the loss when your batch size is equal to 1. In the case, where your batch size is greater than one, you should be careful with the padding of your sequence.

**Comment by dirtdust** [comment]
@bekou  I see, thanks a lot!

**Comment by liujian19911023** [comment]
@dirtdust  are you success change batch size bigger than 1？

**Comment by dirtdust** [comment]
@liujian19911023 no, and the author said currently the batch size can only be set to 1.
