### ISSUE TITLE
About memory usage

### ISSUE THREAD

**Issue by Just4Uzi** [bekou/multihead_joint_entity_relation_extraction#7]
Thank you very much for your great job！
 I try to train this model on my data, but i found that it takes up a lot of memory. And as the training continues, the memory usage is slowly increasing. Is this normal? If I want to reduce the memory usage , where should I start?

![image](https://user-images.githubusercontent.com/19725453/56546681-a5633280-65ad-11e9-8672-c921e3f3a634.png)

**Comment by bekou** [comment]
While running the experiments, I have never exceeded the usage of 4gb for the CoNLL dataset and the usage of 5gb for the DREC dataset. FYI, the size of the DREC data is around 4mb for the training set.
