### ISSUE TITLE
tf_utils.py BUG?

### ISSUE THREAD

**Issue by yuanxiaosc** [bekou/multihead_joint_entity_relation_extraction#9]
Thanks to the author's hard work, I have two questions about this code and I hope to get your answer.

+ Is line 203 redundant?
+ Why batch_size is specified as 1?
> I found that when constructing model input data, there is only one doc content per input as input, but the model's code seems to support small batch input. If I construct a small batch of input data, the model will work properly.

**Comment by bekou** [comment]
Indeed line 203 is redundant. I'll remove it in a next version. 
Concerning the batch size, I have done experiments only with batch size = 1 and thus there are no guarantees that the model will work with different batch sizes.
